import '@/app/globals.css'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './_components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: `Hexvel's portfolio`,
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn('h-full w-full', inter.className)}>
				<Header />
				<main className='min-h-screen flex flex-col items-center justify-center'>
					{children}
				</main>
			</body>
		</html>
	)
}
